name: nysse_asemanaytto
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  fixnum: ^1.1.1
  fl_chart: ^0.70.2
  flutter_map: ^7.0.2
  flutter_map_cancellable_tile_provider: ^3.0.2
  flutter_svg: ^2.0.17
  graphql_flutter: ^5.2.0-beta.8
  http: ^1.3.0
  latlong2: ^0.9.1
  mqtt5_client: ^4.5.3
  protobuf: ^3.1.0
  shared_preferences: ^2.3.5
  xml: ^6.5.0
  multicast_dns: ^0.3.2+7
  meta: ^1.15.0

dev_dependencies:
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/fmi_weather_symbols/

  fonts:
    # Nysse
    - family: LotaGrotesque
      fonts:
        - asset: assets/fonts/Lota-Grotesque-Regular.otf
        - asset: assets/fonts/Lota-Grotesque-Bold.otf
          weight: 700

    # BMW
    - family: BMWTypeNext
      fonts:
        - asset: assets/fonts/BMWTypeNextTT-Regular.ttf
        - asset: assets/fonts/BMWTypeNextTT-Bold.ttf
          weight: 700

    # Philips Hue
    - family: NeueFrutiger
      fonts:
        - asset: assets/fonts/NeueFrutigerWorld-Light.ttf
          weight: 300
        - asset: assets/fonts/NeueFrutigerWorld-Book.ttf
        - asset: assets/fonts/NeueFrutigerWorld-Medium.ttf
          weight: 500
        - asset: assets/fonts/NeueFrutigerWorld-Bold.ttf
          weight: 700

    - family: HueIcons
      fonts:
        - asset: assets/fonts/hue_icons.ttf

    # Default
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Italic.ttf
          style: italic

        - asset: assets/fonts/Lato-Thin.ttf
          weight: 100
        - asset: assets/fonts/Lato-ThinItalic.ttf
          weight: 100
          style: italic

        - asset: assets/fonts/Lato-Light.ttf
          weight: 300
        - asset: assets/fonts/Lato-LightItalic.ttf
          weight: 300
          style: italic

        - asset: assets/fonts/Lato-Bold.ttf
          weight: 700
        - asset: assets/fonts/Lato-BoldItalic.ttf
          weight: 700
          style: italic

        - asset: assets/fonts/Lato-Black.ttf
          weight: 900
        - asset: assets/fonts/Lato-BlackItalic.ttf
          weight: 900
          style: italic

    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Thin.ttf
          weight: 100
        - asset: assets/fonts/Inter-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Inter-Black.ttf
          weight: 900
