name: nysse_asemanaytto
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: LotaGrotesque
      fonts:
        - asset: assets/fonts/Lota-Grotesque-Regular.otf
        - asset: assets/fonts/BMWTypeNextTT-Bold.ttf
          weight: 700

    - family: BMWTypeNext
      fonts:
        - asset: assets/fonts/BMWTypeNextTT-Bold.ttf
        - asset: assets/fonts/BMWTypeNextTT-Bold.ttf
          weight: 700
